grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  module_0:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: kd_tree
      weights: uniform
      n_neighbors: 3
    search_param_grid:
      algorithm:
        - auto
        - ball_tree
        - kd_tree
        - brute
      weights:
        - uniform
        - distance
      n_neighbors:
        - 3
        - 5
        - 9

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
        - 10
        - 15
        - 20
      max_features:
        - sqrt
        - log2
      n_estimators:
        - 3
        - 5
        - 9

    module_2:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      solver: saga
      max_iter: 100
    search_param_grid:
      penalty:
        - l1
        - l2
      solver:
        - saga
      max_iter:
        - 100
        - 200