columns:
  - SeniorCitizen: category
  - Dependents: category
  - tenure: int
  - MultipleLines: category
  - InternetService: category
  - OnlineSecurity: category
  - TechSupport: category
  - StreamingTV: category
  - StreamingMovies: category
  - Contract: category
  - PaperlessBilling: category
  - PaymentMethod: category
  - MonthlyCharges: float
  - TotalCharges: float

numerical_columns:
  - tenure
  - MonthlyCharges
  - TotalCharges

categorical_columns:
  - SeniorCitizen
  - Dependents
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod

drop_columns: 
  - customerID
  - gender
  - Partner
  - PhoneService
  - OnlineBackup
  - DeviceProtection

or_columns: []

oh_columns:
  - SeniorCitizen
  - Dependents
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod

num_features: #added
  - tenure
  - MonthlyCharges
  - TotalCharges

transform_columns:
  - tenure
  - MonthlyCharges
  - TotalCharges